### ISSUE TITLE
compileGsonViews error in java 1.8.0_112 and gradle 3.3

### ISSUE THREAD

**Issue by beneo** [grails/grails-views#107]
1. create grails 3.2.4 app with default profile 
2. add json view dependency and plugin in build.gradle 
3. add new controller and add one gson under views 
4. run `gradle clean && gradle -Dgrails.env=development assemble` you can get the error message 
5. the json view version is 1.1.3
6. i think that is an issue

   

> :compileGsonViews
    Exception in thread "main" java.lang.RuntimeException: conversion of true to boolean not implemented
                at org.grails.config.CodeGenConfig.convertToOtherTypes(CodeGenConfig.groovy:213)
                at org.grails.config.CodeGenConfig.convertToType(CodeGenConfig.groovy:208)
                at org.grails.config.CodeGenConfig.getProperty(CodeGenConfig.groovy:264)
        at grails.views.GenericViewConfiguration$Trait$Helper.readConfiguration(GenericViewConfiguration.groovy:117)
        at grails.views.GenericViewConfiguration$Trait$Helper$readConfiguration$6.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at grails.plugin.json.view.JsonViewConfiguration.readConfiguration(JsonViewConfiguration.groovy)
        at grails.views.GenericViewConfiguration$Trait$Helper.readConfiguration(GenericViewConfiguration.groovy:98)
        at grails.views.GenericViewConfiguration$Trait$Helper$readConfiguration$5.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at grails.plugin.json.view.JsonViewConfiguration.readConfiguration(JsonViewConfiguration.groovy)
        at grails.views.GenericViewConfiguration$readConfiguration$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at grails.views.AbstractGroovyTemplateCompiler.run(AbstractGroovyTemplateCompiler.groovy:101)
        at grails.plugin.json.view.JsonViewCompiler.main(JsonViewCompiler.groovy:41)
:compileGsonViews FAILED

[mobile.zip](https://github.com/grails/grails-views/files/695642/mobile.zip)

**Comment by beneo** [comment]
i use grails 3.1.14, 3.1.11
gradle 2.14, 2.14.1, 2.13

the exception will appear again

**Comment by jameskleeh** [comment]
This is fixed in Grails 3.2.5 https://github.com/grails/grails-core/commit/0dfdd0a525ce9f4639c12a5387c9d13694dcdccb
