### ISSUE TITLE
Problem rendering circular references

### ISSUE THREAD

**Issue by jeffbrown** [grails/grails-views#165]
From https://stackoverflow.com/questions/49389879/grails-v3-3-3-json-views-1-2-7-getting-stack-overflow-when-doing-a-deep-rende.

See the project at https://github.com/jeffbrown/williamwoodman.  Run the app and send a request to http://localhost:8080/customer to demonstrate the StackOverflow.

```
Caused by: java.lang.StackOverflowError: null
        at java.lang.String.<init>(String.java:201)
        at java.lang.String.substring(String.java:1957)
        at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:301)
        at java.net.URL.<init>(URL.java:615)
        at java.net.URL.<init>(URL.java:483)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:365)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at grails.plugin.json.view.api.internal.DefaultGrailsJsonViewHelper$_process_closure7.doCall(DefaultGrailsJsonViewHelper.groovy:547)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.cloneDelegateAndGetContent(StreamingJsonBuilder.java:793)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.call(StreamingJsonBuilder.java:665)
        at grails.plugin.json.view.api.internal.DefaultGrailsJsonViewHelper.process(DefaultGrailsJsonViewHelper.groovy:544)
        at grails.plugin.json.view.api.internal.DefaultGrailsJsonViewHelper.process(DefaultGrailsJsonViewHelper.groovy:479)
        at grails.plugin.json.view.api.internal.DefaultGrailsJsonViewHelper$_process_closure9.doCall(DefaultGrailsJsonViewHelper.groovy:606)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.curryDelegateAndGetContent(StreamingJsonBuilder.java:809)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.writeObject(StreamingJsonBuilder.java:775)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.writeCollectionWithClosure(StreamingJsonBuilder.java:766)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.writeObjects(StreamingJsonBuilder.java:706)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.call(StreamingJsonBuilder.java:610)
        at grails.plugin.json.view.api.internal.DefaultGrailsJsonViewHelper.process(DefaultGrailsJsonViewHelper.groovy:604)
        at grails.plugin.json.view.api.internal.DefaultGrailsJsonViewHelper$_process_closure7.doCall(DefaultGrailsJsonViewHelper.groovy:547)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.cloneDelegateAndGetContent(StreamingJsonBuilder.java:793)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.call(StreamingJsonBuilder.java:665)
        at grails.plugin.json.view.api.internal.DefaultGrailsJsonViewHelper.process(DefaultGrailsJsonViewHelper.groovy:544)
        at grails.plugin.json.view.api.internal.DefaultGrailsJsonViewHelper.process(DefaultGrailsJsonViewHelper.groovy:479)
        at grails.plugin.json.view.api.internal.DefaultGrailsJsonViewHelper$_process_closure9.doCall(DefaultGrailsJsonViewHelper.groovy:606)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.curryDelegateAndGetContent(StreamingJsonBuilder.java:809)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.writeObject(StreamingJsonBuilder.java:775)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.writeCollectionWithClosure(StreamingJsonBuilder.java:766)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.writeObjects(StreamingJsonBuilder.java:706)
        at grails.plugin.json.builder.StreamingJsonBuilder$StreamingJsonDelegate.call(StreamingJsonBuilder.java:610)
```

The relevant files:

https://github.com/jeffbrown/williamwoodman/blob/master/grails-app/domain/williamwoodman/Customer.groovy

```groovy
package williamwoodman

class Customer {
    String name
    static hasMany = [sites: Site]
}
```

https://github.com/jeffbrown/williamwoodman/blob/master/grails-app/domain/williamwoodman/Site.groovy

```groovy
package williamwoodman

class Site {
    String name
    static belongsTo = [customer: Customer]
}
```

The problematic template:

https://github.com/jeffbrown/williamwoodman/blob/master/grails-app/views/customer/_customer.gson

```groovy
import williamwoodman.Customer

model {
    Customer customer
}

json g.render(customer, [deep: true])
```

**Comment by smakela** [comment]
Good this bug is here, because I was also about to report this. Is there timeline when @ilopmar can start working on this issue? Maybe I can help with this one too?

**Comment by jameskleeh** [comment]
@smakela A PR would be welcome

**Comment by smakela** [comment]
> @smakela A PR would be welcome

I'll try to look in to this, because I have also a real world example for this in our model plugin.

**Comment by ilopmar** [comment]
@smakela I'll start working on this as soon as I can, I have other commitments. In the mean time, if you want to work on this a send a PR, please let us know.

**Comment by smakela** [comment]
Dumb question but how can I debug functional tests with this project in the IntelliJ?
It must be something to do with the Gradle daemon. If I try to verification -> check task with "Debug" the debugger does not attach. Is there a good wiki for this?

**Comment by jameskleeh** [comment]
@smakela If I do as you said - right click on check task -> debug, the breakpoints I have set are hit. I would recommend cleaning and stopping any gradle daemons

**Comment by smakela** [comment]
I think I have solution for this. Have to test a little bit more and then I will make PR and you guys can check it out.

**Comment by smakela** [comment]
> @smakela If I do as you said - right click on check task -> debug, the breakpoints I have set are hit. I would recommend cleaning and stopping any gradle daemons

Ok. This was not working with IntelliJ 2018.1.x, but now I updated to the 2018.2.4 and everything started to work magically.

**Comment by abcfy2** [comment]
I have the same issue. Not fixed yet ?

**Comment by smakela** [comment]
> I have the same issue. Not fixed yet ?

@abcfy2 I have provided pull request to fix this issue, but it has not been verified by the Grails crew.

**Comment by smakela** [comment]
@jameskleeh or @ilopmar This can be closed. I think I forgot some commit tag so this was not automatically closed.
