### ISSUE TITLE
Views for domain class named Generator causes exception

### ISSUE THREAD

**Issue by crbudzeak** [grails/grails-views#172]
All components were generated with grails commands.

1. grails create-app jsonGenerator
2. ./grailsw create-domain-class jsongenerator.Generator
3. ./grailsw generate-all jsongenerator.Generator
4. ./grailsw create-domain-class jsongenerator.Control
5. ./grailsw generate-all jsongenerator.Control

Added the URL mappings as /generators and /controls and BootStrap.groovy creates one of each object.

./gradlew bootRun

> curl http://localhost:8080/controls
`[{"id":1,"name":"Works"}]`

> curl http://localhost:8080/generators
`{"message":"Internal server error","error":500}`

```
2018-06-28 16:55:02.641 ERROR --- [nio-8080-exec-3] o.g.web.errors.GrailsExceptionResolver   : MultipleCompilationErrorsException occurred when processing request: [GET] /generators
startup failed:
jsonGenerator_generator__generator_gson: -1: The return type of jsongenerator.Generator getGenerator() in jsonGenerator_generator__generator_gson is incompatible with grails.plugin.json.builder.JsonGenerator in grails.plugin.json.view.JsonViewWritableScript
. At [-1:-1]  @ line -1, column -1.
1 error
. Stacktrace follows:

java.lang.reflect.InvocationTargetException: null
        at org.grails.core.DefaultGrailsControllerClass$ReflectionInvoker.invoke(DefaultGrailsControllerClass.java:211)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: grails.views.ViewRenderException: Error rendering view: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
jsonGenerator_generator__generator_gson: -1: The return type of jsongenerator.Generator getGenerator() in jsonGenerator_generator__generator_gson is incompatible with grails.plugin.json.builder.JsonGenerator in grails.plugin.json.view.JsonViewWritableScript
. At [-1:-1]  @ line -1, column -1.
1 error

        at grails.views.AbstractWritableScript.writeTo(AbstractWritableScript.groovy:43)
        at grails.views.mvc.GenericGroovyTemplateView.renderMergedOutputModel(GenericGroovyTemplateView.groovy:73)
        at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
        at grails.views.mvc.renderer.DefaultViewRenderer.render(DefaultViewRenderer.groovy:111)
        at grails.artefact.controller.RestResponder$Trait$Helper.internalRespond(RestResponder.groovy:188)
        at grails.artefact.controller.RestResponder$Trait$Helper.respond(RestResponder.groovy:62)
        at jsongenerator.GeneratorController.index(GeneratorController.groovy:15)
        ... 14 common frames omitted
Caused by: grails.views.ViewCompilationException: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
jsonGenerator_generator__generator_gson: -1: The return type of jsongenerator.Generator getGenerator() in jsonGenerator_generator__generator_gson is incompatible with grails.plugin.json.builder.JsonGenerator in grails.plugin.json.view.JsonViewWritableScript
. At [-1:-1]  @ line -1, column -1.
1 error

        at grails.views.ResolvableGroovyTemplateEngine$_createTemplate_closure2.doCall(ResolvableGroovyTemplateEngine.groovy:423)
        at grails.views.ResolvableGroovyTemplateEngine.createTemplate(ResolvableGroovyTemplateEngine.groovy:417)
        at grails.views.ResolvableGroovyTemplateEngine.attemptResolvePath(ResolvableGroovyTemplateEngine.groovy:181)
        at grails.views.ResolvableGroovyTemplateEngine$_closure1.doCall(ResolvableGroovyTemplateEngine.groovy:61)
        at grails.views.ResolvableGroovyTemplateEngine.resolveTemplate(ResolvableGroovyTemplateEngine.groovy:363)
        at grails.plugin.json.view.api.internal.DefaultGrailsJsonViewHelper.render(DefaultGrailsJsonViewHelper.groovy:758)
        at grails.plugin.json.view.api.internal.TemplateRenderer.invokeMethod(TemplateRenderer.groovy:39)
        at jsonGenerator_generator_index_gson.run(jsonGenerator_generator_index_gson:7)
        at grails.plugin.json.view.JsonViewWritableScript.doWrite(JsonViewWritableScript.groovy:28)
        at grails.views.AbstractWritableScript.writeTo(AbstractWritableScript.groovy:40)
        ... 20 common frames omitted
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
jsonGenerator_generator__generator_gson: -1: The return type of jsongenerator.Generator getGenerator() in jsonGenerator_generator__generator_gson is incompatible with grails.plugin.json.builder.JsonGenerator in grails.plugin.json.view.JsonViewWritableScript
. At [-1:-1]  @ line -1, column -1.
1 error

        at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
        at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
        at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
        at grails.views.ResolvableGroovyTemplateEngine$_createTemplate_closure2.doCall(ResolvableGroovyTemplateEngine.groovy:420)
        ... 29 common frames omitted
```

[stacktrace.txt](https://github.com/grails/grails-views/files/2146955/stacktrace.txt)

[jsonGenerator-bug-report-28062018.zip](https://github.com/grails/grails-views/files/2146961/jsonGenerator-bug-report-28062018.zip)

**Comment by ilopmar** [comment]
The problem is because `generator` is a reserved keyword and it can't be used for a model name. I've updated the documentation to include it in the list: http://views.grails.org/snapshot/#_model_naming

To make it work you can rename the variable:
``` 
// index.gson
import jsongenerator.Generator

model {
    Iterable<Generator> generatorList
}

json tmpl.generator("gen", generatorList)
```

```
// _generator.gson
import jsongenerator.Generator

model {
    //Generator generator <--- Problem!
    Generator gen
}

json g.render(gen, [resolveTemplate: false])
```
The issue is that when defining `generator` in the model groovy will create a getter for that property that collides with this getter: https://github.com/grails/grails-views/blob/3977f2ce9d0ea48c184b64c02fcecc5c9261227d/json/src/main/groovy/grails/plugin/json/view/api/internal/DefaultJsonViewHelper.groovy#L245
