### ISSUE TITLE
New Feature: Support for GSON views defined by plugins

### ISSUE THREAD

**Issue by droggo** [grails/grails-views#26]
I have created a sample app to demonstrate this here: https://github.com/droggo/GsonViews
It looks like any ".gson" file located in a plugin will not be resolved in application. We have explicitly set `views-json:1.0.8`, by default 1.0.4 was used. Grails version is 3.1.5

Following endpoints can be checked:
* http://localhost:8080/app/appView

Standard gson view defined in application. Working fine. Can also be accessed from plugin controller using `http://localhost:8080/plugin/appView`

* http://localhost:8080/app/appTemplate

gson view which renders gson template also from application. Working fine.

* http://localhost:8080/app/pluginTemplate

gson view which renders gson template from plugin using:
`json g.render(template: '/plugintemplate/plugintemplate', plugin: 'GsonPlugin')`. Throws exception `grails.views.ViewException: Template not found for name /plugintemplate/plugintemplate`.
Also tried without 'plugin' parameter but no difference

* http://localhost:8080/plugin/pluginView

gson view defined in plugin. Throws exception `javax.servlet.ServletException: Could not resolve view with name 'pluginView' in servlet with name 'grailsDispatcherServlet'`

* http://localhost:8080/plugin/pluginTemplate

gson view defined in plugin, rendering gson template from the same plugin. Throws exception `javax.servlet.ServletException: Could not resolve view with name 'pluginTemplate' in servlet with name 'grailsDispatcherServlet'`

Impact is that we are not able to define any gson views or templates in plugins, everything must be defined in Application. Are we doing something wrong or is it a bug? If we can prepare something more let us know.

Shortened stacktrace for Template not found:
```
grails.views.ViewException: Template not found for name /plugintemplate/plugintemplate
        at grails.plugin.json.view.api.internal.JsonGrailsViewHelper.render(JsonGrailsViewHelper.groovy:345)
        at GsonApp_app_pluginTemplate_gson.run(GsonApp_app_pluginTemplate_gson:1)
        at grails.plugin.json.view.JsonViewTemplate.doWrite(JsonViewTemplate.groovy:32)
        at grails.views.AbstractWritableScript.writeTo(AbstractWritableScript.groovy:30)
        at grails.views.mvc.GenericGroovyTemplateView.renderMergedOutputModel(GenericGroovyTemplateView.groovy:64)
```

Stacktrace for could not resolve view:
```
ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Could not resolve view with name 'pluginView' in servlet with name 'grailsDispatcherServlet'] with root cause
javax.servlet.ServletException: Could not resolve view with name 'pluginView' in servlet with name 'grailsDispatcherServlet'
        at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1226)
        at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1027)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:968)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:859)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:844)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration$ApplicationContextHeaderFilter.doFilterInternal(EndpointWebMvcAutoConfiguration.java:237)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicatirChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:112)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:75)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
        at org.apaalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ColinHarrington** [comment]
Plugin views have some support but the resolution has some issues  see [TestGsonControllerSpec.groovy#L48](https://github.com/grails/grails-views/blob/master/functional-tests/src/integration-test/groovy/functional/tests/TestGsonControllerSpec.groovy#L48)

The compiled views and templates are available but the resolution mechanism isn't consistent.

**Comment by ColinHarrington** [comment]
Basically resolution of json-views & templates is broken when the `plugin.fileSystemShortName` doesn't match the project.name of the plugin.
