### ISSUE TITLE
StackOverflowError when trying to render a Domain class error with a nested Domain object

### ISSUE THREAD

**Issue by marcDeSantis** [grails/grails-views#33]
When a domain object has nested objects:
```
  class RolePermission  {

    Role role
    Permission permission
```

any constraint that causes this to fail validation will cause a StackOverFlowError when attempting to render the error in a gson view:
```
java.lang.StackOverflowError: null
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:100)
	at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:62)
	at groovy.lang.PropertyValue.getValue(PropertyValue.java:42)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.getProperties(DefaultGroovyMethods.java:389)
	at grails.plugin.json.builder.JsonOutput.writeObject(JsonOutput.java:327)
	at grails.plugin.json.builder.JsonOutput.writeArray(JsonOutput.java:365)
	at grails.plugin.json.builder.JsonOutput.writeObject(JsonOutput.java:308)
	at grails.plugin.json.builder.JsonOutput.writeMap(JsonOutput.java:460)
	at grails.plugin.json.builder.JsonOutput.writeObject(JsonOutput.java:331)
	at grails.plugin.json.builder.JsonOutput.writeArray(JsonOutput.java:365)
```

Sample template:
```
model {
    Errors errors
}

response.status UNPROCESSABLE_ENTITY

json {
    Errors errorsObject = (Errors)this.errors
    def allErrors = errorsObject.allErrors
    int errorCount = allErrors.size()

    message "There was an error processing your request."
    source Metadata.getCurrent().getApplicationName()
    total errorCount
    errors(allErrors) { FieldError error ->
        field error.field
        value error.rejectedValue
    }
}
```

`error.rejectedValue` is what is causing the recursion error. Oddly enough, this works fine if you do not have an error view, since it uses a default error renderer. It also works fine when the nested Object is a POGO and not a Domain class.

**Comment by graemerocher** [comment]
you will need to use `value g.render(error.rejectedValue)`

**Comment by graemerocher** [comment]
closing since I believe the solution suggested above is the correct one
