### ISSUE TITLE
Possible memory leak in GenericGroovyTemplateView

### ISSUE THREAD

**Issue by benorama** [grails/grails-views#34]
We are getting memory leak issue which looks like to be related to GSON views.

```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3181)
	at java.util.ArrayList.grow(ArrayList.java:261)
	at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
	at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
	at java.util.ArrayList.add(ArrayList.java:458)
	at grails.views.ResolvableGroovyTemplateEngine.resolveTemplate(ResolvableGroovyTemplateEngine.groovy:270)
	at grails.views.mvc.GenericGroovyTemplateView.renderMergedOutputModel(GenericGroovyTemplateView.groovy:52)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
	at grails.views.mvc.renderer.DefaultViewRenderer.render(DefaultViewRenderer.groovy:94)
	at grails.artefact.controller.RestResponder$Trait$Helper.internalRespond(RestResponder.groovy:188)
	at grails.artefact.controller.RestResponder$Trait$Helper.respond(RestResponder.groovy:98)
	at grails.artefact.controller.RestResponder$Trait$Helper$respond$2.call(Unknown Source)
	at agorapulse.analytics.api.ManagerController.respond(ManagerController.groovy)
	at grails.artefact.controller.RestResponder$Trait$Helper.respond(RestResponder.groovy)
	at grails.artefact.controller.RestResponder$Trait$Helper$respond$1.call(Unknown Source)
	at agorapulse.analytics.api.ManagerController.respond(ManagerController.groovy)
	at grails.artefact.controller.RestResponder$respond.callCurrent(Unknown Source)
	at agorapulse.analytics.api.ManagerController.show(ManagerController.groovy:36)
	at java.lang.invoke.LambdaForm$DMH/697974451.invokeVirtual_L_L(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$BMH/395661402.reinvoke(LambdaForm$BMH)
	at java.lang.invoke.LambdaForm$MH/1116396857.invoke_MT(LambdaForm$MH)
	at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:222)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:187)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:968)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:859)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:844)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
```

When looking at code in [ResolvableGroovyTemplateEngine.groovy](https://github.com/grails/grails-views/blob/master/core/src/main/groovy/grails/views/ResolvableGroovyTemplateEngine.groovy) at L. 270, there is a while loop that could go infinite with `qualifiedPaths` growing and taking all the memory?

The line generating the issue in our controller is a simple `respond manager`.

The `manager/show.gson` is as follow:
```
import agorapulse.analytics.Manager

model {
    Manager manager
}

json tmpl.manager(manager)
```

And calls the following `manager/_manager.gson`:
```
import agorapulse.analytics.Manager

model {
    Manager manager
}

// Note: use basic json rendering instead of domain rendering to be able to add profileType (transient property)
json {
    id manager.id
    dateCreated manager.dateCreated
    email manager.email
    emailValidated manager.emailValidated
    invitationCount manager.invitationCount
    name manager.name
    profileImageUrl manager.profileImageUrl
    profileType manager.profileType
    recentSyncCount manager.recentSyncCount
    referralCount manager.referralCount
    referralToken manager.referralToken
    termsAccepted manager.termsAccepted
    twitterId manager.twitterId
    twitterScreenName manager.twitterScreenName
}
``` 

It's a random error that's pretty difficult to reproduce locally. But it happens pretty often on prod.
Any idea to workaround it?

**Comment by benorama** [comment]
I'm using **1.0.7**, so I'm going to test with **1.0.9**, to see if it solves the issue.

**Comment by csoete** [comment]
maybe related to my issue #40
