### ISSUE TITLE
Improve stacktrace for nullpointers

### ISSUE THREAD

**Issue by dularion** [grails/grails-views#56]
So when we currently get a nullpointer or some other error inside of the gson views we often have to struggle to find the origin of the error. We see things like: 

``` bash
Caused by: grails.views.ViewRenderException: Error rendering view: BUG! exception in phase 'instruction selection' in source unit 'kcenter_feedConfig__feedConfig_gson' unexpected NullpointerException
    at grails.views.AbstractWritableScript.writeTo(AbstractWritableScript.groovy:33)
    at grails.views.mvc.GenericGroovyTemplateView.renderMergedOutputModel(GenericGroovyTemplateView.groovy:65)
    at grails.views.mvc.renderer.DefaultViewRenderer.render(DefaultViewRenderer.groovy:94)
    at grails.artefact.controller.RestResponder$Trait$Helper.internalRespond(RestResponder.groovy:188)
    at grails.artefact.controller.RestResponder$Trait$Helper.respond(RestResponder.groovy:62)
    at grails.rest.RestfulController.index(RestfulController.groovy:64)
    at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
    at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
    ... 8 common frames omitted
```

Is there any way to improve this? It slows down our efficiency quite often..

**Comment by graemerocher** [comment]
Please can you provide an example.. thanks
